# Checks of different solutions for a triangular dislocation

in full-space and half-space


## Simple triangle  // to the plane $e_1,\,e_2$

We compare the outputs of Bigwham for displacement and stresses at a set of observation ploints
with:

1 - direct integration of the full-space fundamental kernels (results from mathematica)

2 - integration of the full-space regularized kernels of Li&Mear (results from mathematica)

3 - Matlab code of Nikkho and Walter 

4 - Matlab code for a TI material of Pan et al  

The results from bigwham are with _bm , the others are copy/paste from the other codes with _1_fs, _2_reg, _3_nw, _4_pan 



In [1]:
import numpy as np
from bigwham4py import BEMatrix

coor = np.asarray([[0.,0.,0.],[2.,0.,0.],[0.,1.,0.]])  # vertex coordinates
conn =np.asarray([[0,1,2]])  # connectivity of the triangular dislocation

G=1.
nu=0.35
kernel = "3DT0-H"
elas_prop = np.array([2*G*(1+nu), nu])

# 4 distincts observations point (inside elemt, above, below and away on plane)
obs_points = np.asarray([[0.3,0.3,0.],[0.3,0.3,1.],[0.3,0.3,-1.],[1.3,2.3,0.]])

h = BEMatrix(kernel, coor, conn, elas_prop, 32, 0., 1e-6,n_openMP_threads=8)


--------------------
Creation of a square BigWhamIO object with verbose on
Forcing the number of OpenMP threads to 8
Kernel = 3DT0-H, number of physical properties = 2
--------------------
Hierarchical representation creation ...
Binary cluster tree depth =0
Number of blocks =1
Number of full blocks =1
Number of low rank blocks =0
Hierarchical representation complete.
--------------------
Populating Hierarchical matrix ...
Loop on full blocks construction  
Loop on low rank blocks construction
HMAT num openMP threads = 8
Creation of hmat done in 0.182583 s
Compression ratio - 1
Hmat object - built 
Hierarchical matrix construction complete.
Compression Ratio = 1, eps_aca = 1e-06, eta = 0
Hierarchical matrix total construction time : 0.182632 s
BigWham constructed Hmat of size (1 x 3) X (1 x 3)
--------------------


In [ ]:
# e_1 d
d=np.array([1.,0.,0.])

stress_bm_e1=h.compute_stresses(obs_points,-d)   # minus sign due to convention of positive dd in overlap in the inner of Bigwham....
displ_bm_e1=h.compute_displacements(obs_points,-d)
# e_2 d
d=np.array([0.,1.,0.])

stress_bm_e2=h.compute_stresses(obs_points,-d)   # minus sign due to convention of positive dd in overlap in the inner of Bigwham....
displ_bm_e2=h.compute_displacements(obs_points,-d)
# e_3 d
d=np.array([0.,0.,1.])

stress_bm_e3=h.compute_stresses(obs_points,-d)   # minus sign due to convention of positive dd in overlap in the inner of Bigwham....
displ_bm_e3=h.compute_displacements(obs_points,-d)


### Compare with results from diret integration of FS mma kernels
(notebook )

for the first obs point for direct integration we offset the z by 1e-5

First displacement

In [ ]:
# first obs_point (needs to be perturbed for direct numerical intg-> so results are not good)

displ_1_fs_= np.array([[0.501044, 0.000798025, 0.0104277], [0.000798025, 0.500757, 
  0.0137058], [-0.0175464, -0.0138553, 0.500786]])

displ_bm_point_1 = np.array([displ_bm_e1[0],displ_bm_e2[0],displ_bm_e3[0]]).T
displ_1_fs_-displ_bm_point_1


array([[ 0.001044  ,  0.00079802, -0.01075888],
       [ 0.00079802,  0.000757  ,  0.00095212],
       [ 0.00364018, -0.00110162,  0.000786  ]])

In [ ]:
# second obs_point   [0.3, 0.3, 1. ]
displ_1_fs_= np.array([[0.0278836, -0.00127375, -0.0154156], [-0.00127375, 
  0.0185273, -0.00570123], [-0.0212, -0.00712306, 0.119758]])
displ_bm_point_2 = np.array([displ_bm_e1[1],displ_bm_e2[1],displ_bm_e3[1]]).T
displ_1_fs_-displ_bm_point_2

In [ ]:
# third obs_point   [0.3, 0.3, -1. ]
displ_1_fs_=np.array([[-0.0278836, 
  0.00127375, -0.0154156], [0.00127375, -0.0185273, -0.00570123], 
[-0.0212, -0.00712306, -0.119758]])
displ_bm_point_3 = np.array([displ_bm_e1[2],displ_bm_e2[2],displ_bm_e3[2]]).T
displ_1_fs_-displ_bm_point_3
#displ_bm_point_3

array([[-0.02788357,  0.00127375, -0.01541562],
       [ 0.00127375, -0.0185273 , -0.00570123],
       [-0.0212    , -0.00712306, -0.11975815]])

In [31]:
# fourth obs_point   [1.3, 2.3, 0. ]
displ_1_fs_=np.array([[0., 0., -0.00128824], [0., 0., -0.00385178], [0.00128824, 
  0.00385178, 0.]])
displ_bm_point_4 = np.array([displ_bm_e1[3],displ_bm_e2[3],displ_bm_e3[3]]).T
displ_1_fs_-displ_bm_point_4
displ_bm_point_4

array([[ 0.        ,  0.        , -0.00128824],
       [ 0.        ,  0.        , -0.00385178],
       [ 0.00128824,  0.00385178,  0.        ]])

Now stresses

In [ ]:
def from_vect_to_stress(st):
    return np.array([[st[0],st[3],st[4]],[st[3],st[1],st[5]],[st[4],st[5],st[2]]])

# fourth obs_point   [1.3, 2.3, 0. ]  - along e_1
stress_1_fs_e1=np.array([[0., 0., 0.00608067], [0., 
  0., 0.00387974], [0.00608067, 0.00387974, 0.]])
stress_bm_point_4_e1 = from_vect_to_stress(stress_bm_e1[3])
stress_bm_point_4_e1-stress_1_fs_e1

array([[-1.21018423e-11, -9.21987712e-11,  4.02736505e-09],
       [-9.21987712e-11, -3.31828699e-10, -2.80809874e-09],
       [ 4.02736505e-09, -2.80809874e-09,  9.29542003e-11]])

In [47]:
# fourth obs_point   [1.3, 2.3, 0. ]  - along e_2
stress_1_fs_e2=np.array([[0., 0., 0.00387974], [0., 0., 0.0160709], [0.00387974, 0.0160709, 
  0.]])
stress_bm_point_4_e2 = from_vect_to_stress(stress_bm_e2[3])
stress_bm_point_4_e2-stress_1_fs_e2

array([[-1.05633773e-10, -3.27180989e-10, -2.80809874e-09],
       [-3.27180989e-10, -8.88556364e-10, -3.97605318e-08],
       [-2.80809874e-09, -3.97605318e-08,  2.68700037e-10]])

In [48]:
# fourth obs_point   [1.3, 2.3, 0. ]  - along e_3
stress_1_fs_e3=np.array([[0.00712989, 0.00332549, 0.], [0.00332549, 0.0156929, 0.], [0., 0., 
  0.0134252]])
stress_bm_point_4_e3 = from_vect_to_stress(stress_bm_e3[3])
stress_bm_point_4_e3-stress_1_fs_e3

array([[-1.93612578e-09, -9.78370347e-10,  9.29542003e-11],
       [-9.78370347e-10,  4.81710553e-09,  2.68700037e-10],
       [ 9.29542003e-11,  2.68700037e-10, -2.77170707e-08]])

In [50]:
# third obs_point   [0.3, 0.3, -1. ]  - along e_1
stress_1_fs_e1=np.array([[-0.0207403, 0.00713607, 0.0118613], [0.00713607, 0.00902023, 
  0.00606929], [0.0118613, 0.00606929, -0.0871421]])
stress_bm_point_3_e1 = from_vect_to_stress(stress_bm_e1[2])
stress_bm_point_3_e1-stress_1_fs_e1

array([[ 7.56886817e-09, -1.28896973e-09, -2.42847019e-08],
       [-1.28896973e-09,  1.40774036e-09, -4.89177135e-10],
       [-2.42847019e-08, -4.89177135e-10, -1.46943542e-08]])

In [53]:
# third obs_point   [0.3, 0.3, -1. ]  - along e_2
stress_1_fs_e2=np.array([[0.00649485, 0.010851, 0.00606929], [0.010851, 0.00131676, 
  0.057033], [0.00606929, 0.057033, -0.0424372]])
stress_bm_point_3_e2 = from_vect_to_stress(stress_bm_e2[2])
stress_bm_point_3_e2-stress_1_fs_e2

array([[ 4.07618461e-09,  1.24395505e-08, -4.89177135e-10],
       [ 1.24395505e-08, -7.43098624e-10,  1.23360897e-08],
       [-4.89177135e-10,  1.23360897e-08, -3.61475185e-09]])

In [56]:
# third obs_point   [0.3, 0.3, -1. ]  - along e_3
stress_1_fs_e3=np.array([[0.00817504, 0.00619666, -0.0871421], [0.00619666, 
  0.0542824, -0.0424372], [-0.0871421, -0.0424372, -0.410047]])
stress_bm_point_3_e3 = from_vect_to_stress(stress_bm_e3[2])
stress_bm_point_3_e3-stress_1_fs_e3

array([[-2.14896581e-09,  4.75225999e-09, -1.46943542e-08],
       [ 4.75225999e-09,  2.24348835e-09, -3.61475185e-09],
       [-1.46943542e-08, -3.61475185e-09, -2.29765248e-07]])

In [ ]:
# first obs_point   [0.3, 0.3, 0. ]  - along e_3
stress_1_fs_e3=np.array([[-1.4834, -0.00766945, -0.000324635], [-0.00766945, -1.5359, \
-0.0050124], [-0.000324635, -0.0050124, -1.78277]])  # computed for x_3 = 0.0001 (not strictly 0) - so not correct for off diag terms
stress_bm_point_1_e3 = from_vect_to_stress(stress_bm_e3[0])
stress_bm_point_1_e3-stress_1_fs_e3

array([[-3.04486853e-05, -2.17062599e-05,  3.24607841e-04],
       [-2.17062599e-05, -1.11417886e-02,  5.01237732e-03],
       [ 3.24607841e-04,  5.01237732e-03,  1.39272176e-04]])

# comparison with Nikko & Walter 
- we offset the half-space kernel to -1000 to mimick full-space conditions


In [ ]:
# point 1  All Displacement
disp_all_pt1_nw_ = np.array([
    [0.5000 ,  -0.0000  ,  0.0212],
  [ -0.0000 ,   0.5000  ,  0.0128],
   [-0.0212 ,  -0.0128   , 0.5000]])
displ_bm_point_1-disp_all_pt1_nw_

array([[ 0.00000000e+00,  0.00000000e+00, -1.34192770e-05],
       [ 0.00000000e+00,  0.00000000e+00, -4.63192113e-05],
       [ 1.34192770e-05,  4.63192113e-05,  0.00000000e+00]])

In [ ]:
# point 1   stress along e_1 in vector format
stress_pt1_e1_nw_ = np.array([ 0.0000 ,   0.0000   , 0.0000 ,   0.0000 ,  -1.2488 ,  -0.0029])

stress_bm_e1[0]

print("N&W")
print(from_vect_to_stress(stress_pt1_e1_nw_))
print("Bigwham")
print(from_vect_to_stress(stress_bm_e1[0]))


N&W
[[ 0.      0.     -1.2488]
 [ 0.      0.     -0.0029]
 [-1.2488 -0.0029  0.    ]]
Bigwham
[[ 9.63161095e-08  4.92798278e-09 -1.43356374e+00]
 [ 4.92798278e-09  4.17242077e-09 -8.97301564e-03]
 [-1.43356374e+00 -8.97301564e-03 -2.71590622e-08]]


In [ ]:
# point 1   stress along e_2 in vector format
stress_pt1_e2_nw_ = np.array([     0.0000  ,  0.0000  , 0.0000  ,  0.0000 ,  -0.0029 ,  -1.2731])
stress_bm_e2[0]

print("N&W")
print(from_vect_to_stress(stress_pt1_e2_nw_))
print("Bigwham")
print(from_vect_to_stress(stress_bm_e2[0]))


N&W
[[ 0.      0.     -0.0029]
 [ 0.      0.     -1.2731]
 [-0.0029 -1.2731  0.    ]]
Bigwham
[[ 6.06220531e-09  2.81446766e-09 -8.97301564e-03]
 [ 2.81446766e-09  7.78702618e-08 -1.50777697e+00]
 [-8.97301564e-03 -1.50777697e+00 -2.26844506e-08]]


In [ ]:
# point 1   stress along e_3 in vector format
stress_pt1_e3_nw_ = np.array([ -2.6469, -2.7604 ,  -3.1808 ,  -0.0137 ,  -0.0000  , -0.0000])
stress_bm_e3[0]

print("N&W")
print(from_vect_to_stress(stress_pt1_e3_nw_))
print("Bigwham")
print(from_vect_to_stress(stress_bm_e3[0]))

N&W
[[-2.6469 -0.0137 -0.    ]
 [-0.0137 -2.7604 -0.    ]
 [-0.     -0.     -3.1808]]
Bigwham
[[-1.48343045e+00 -7.69115626e-03 -2.71590622e-08]
 [-7.69115626e-03 -1.54704179e+00 -2.26844506e-08]
 [-2.71590622e-08 -2.26844506e-08 -1.78263073e+00]]


In [112]:
# point 2 
print(obs_points[1])
disp_all_pt2_nw_ = np.array([
    [0.0279 ,  -0.0013  , -0.0154],
  [-0.0013  ,  0.0185  , -0.0057],
   [-0.0212 ,  -0.0071 ,   0.1198]])
displ_bm_point_2-disp_all_pt2_nw_
print("N&W disp")
print(disp_all_pt2_nw_)
print("Biwgham disp")
print(displ_bm_point_2)

# point 2   stress along e_3 in vector format
stress_pt2_e3_nw_ = np.array([   -0.1025,   -0.0729 ,  -0.4448  ,  0.0040  ,  0.0666  ,  0.0325])
stress_bm_e3[1]

print("N&W - stress for tensile")
print(from_vect_to_stress(stress_pt2_e3_nw_))
print("Bigwham - stress for tensile")
print(from_vect_to_stress(stress_bm_e3[1]))

# point 2   stress along e_1 in vector format
stress_pt2_e1_nw_ =np.array([   -0.0532,   -0.0192 ,  -0.1040   , 0.0035 ,   0.0022 ,  -0.0050
])
stress_bm_e1[1]

print("N&W - stress shear e_1")
print(from_vect_to_stress(stress_pt2_e1_nw_))
print("Bigwham - stress for shear e_1")
print(from_vect_to_stress(stress_bm_e1[1]))

[0.3 0.3 1. ]
N&W disp
[[ 0.0279 -0.0013 -0.0154]
 [-0.0013  0.0185 -0.0057]
 [-0.0212 -0.0071  0.1198]]
Biwgham disp
[[ 0.02788357 -0.00127375 -0.01541562]
 [-0.00127375  0.0185273  -0.00570123]
 [-0.0212     -0.00712306  0.11975815]]
N&W - stress for tensile
[[-0.1025  0.004   0.0666]
 [ 0.004  -0.0729  0.0325]
 [ 0.0666  0.0325 -0.4448]]
Bigwham - stress for tensile
[[ 0.00817504  0.00619666  0.08714211]
 [ 0.00619666  0.0542824   0.0424372 ]
 [ 0.08714211  0.0424372  -0.41004721]]
N&W - stress shear e_1
[[-0.0532  0.0035  0.0022]
 [ 0.0035 -0.0192 -0.005 ]
 [ 0.0022 -0.005  -0.104 ]]
Bigwham - stress for shear e_1
[[ 0.02074029 -0.00713607  0.01186128]
 [-0.00713607 -0.00902023  0.00606929]
 [ 0.01186128  0.00606929  0.08714211]]


In [113]:
obs_points[1]

array([0.3, 0.3, 1. ])

## Comparison with Pan et al (2014)

- mimicking the fullspace config by offsetting things down to -1000.

In [114]:
# point 2   stress along e_1 in vector format
stress_pan_e1_ = np.array([[0.0207 ,  -0.0071  ,  0.0119 ],[
    -0.0071  , -0.0090  ,  0.0061],[ 0.0119  ,  0.0061   , 0.0871]])  

stress_bm_e1[1]

print("Pan - stress shear e_1")
print(stress_pan_e1_)
print("Bigwham - stress for shear e_1")
print(from_vect_to_stress(stress_bm_e1[1]))
print("Nikkow&Walter - stress shear e_1")
print(from_vect_to_stress(stress_pt2_e1_nw_))


Pan - stress shear e_1
[[ 0.0207 -0.0071  0.0119]
 [-0.0071 -0.009   0.0061]
 [ 0.0119  0.0061  0.0871]]
Bigwham - stress for shear e_1
[[ 0.02074029 -0.00713607  0.01186128]
 [-0.00713607 -0.00902023  0.00606929]
 [ 0.01186128  0.00606929  0.08714211]]
Nikkow&Walter - stress shear e_1
[[-0.0532  0.0035  0.0022]
 [ 0.0035 -0.0192 -0.005 ]
 [ 0.0022 -0.005  -0.104 ]]


In [121]:
0.0532/0.02074029
0.0192/0.00902023
0.0022/0.01186128
0.0035/0.00713607
0.005/0.00606929

0.8238195901003248